site_name: ShunTian 前端
repo_url: https://github.com/shuntian/shuntian-frontend.git
repo_name: GitHub
nav:
  - 简介: index.md
  - 知识积累:
    - 常用工具: 
      - 简介: 01_knowledge/01_tools/index.md
      - python 安装与卸载: 01_knowledge/01_tools/01_python安装与卸载.md
      - Mac 终端命令前缀修改 zsh: 01_knowledge/01_tools/02_mac终端命令前缀修改_zsh.md
    - 功能规则: 
      - 简介: 01_knowledge/02_features/index.md
      - localeCompare 函数的问题: 01_knowledge/02_features/01_localeCompare的问题.md
      - 字符串比较: 01_knowledge/02_features/02_字符串排序.md
    - 最佳实践: 
      - 简介01_knowledge/03_best_practices/index.md
    - 流程规范: 
      - 简介: 01_knowledge/04_process_specification/index.md
    - 常见方案: 
      - 简介: 01_knowledge/05_plan/index.md
    - 业务推进: 
      - 简介: 01_knowledge/06_manage/index.md
  - 评价体系: 
      - 简介: 02_evaluation/index.md
      - 职级画像: 02_evaluation/职级画像.md
      - 面试评价: 02_evaluation/面试评价.md
  - 方法论: 
      - 简介: 03_methodology/index.md
      - 如何构建知识体系: 03_methodology/如何构建知识体系.md
  - 思维成长: 04_thinking/index.md
  - 关于: about.md
theme: 
  name: windmill
  locale: zh_CN
  include_search_page: false
extra_css:
   - 00_assets/css/extra.css
extra:
  version: 1.0
  article_nav_top: false
